version: "3.8"

services:
  grpc-server-proxy:
    build:
      context: .
      dockerfile: Dockerfile-server.Dockerfile
    networks:
      envoymesh:
        aliases:
        - kv-backend-proxy
    ports:
    - "8811:8811"
  grpc-client-proxy:
    build:
      context: .
      dockerfile: Dockerfile-client.Dockerfile
    networks:
      envoymesh:
        aliases:
        - kv-client-proxy
    ports:
    - "9911:9911"
networks:
  envoymesh: {}
